### ISSUE TITLE
I can't seem to find the "fonts"?

### ISSUE THREAD

**Issue by 0Zenchi** [ArtexJay/Obsidian-CyberGlow#100]
In every font option there's a text saying that I should come here for more options, but I looked around and didn't seem to find.
I do admit that I haven't tried using normal font names. And if it's somewhere but I didn't find cause I don't know any better I do apologize.

**Comment by ArtexJay** [comment]
Oh, oops that text is left over from a very old build. I need to change that text.

The fonts are all built into now, theres no need to install them anymore. 

If you wish to change fonts all you need to do is type in the name of a font into the textbox in style settings and it will automatically change the font with fonts that are installed on your system.

**Comment by 0Zenchi** [comment]
Oh I see, thanks! (I'm also excitedly waiting for the fix on the narrowing of the panes, this is by far the best obsidian theme by light years)
