### ISSUE TITLE
Add `.signature` class to the `<cite>` element

### ISSUE THREAD

**Issue by Jexle** [ArtexJay/Obsidian-CyberGlow#2]
While the `signature` class _works_ on `<cite>` elements as far as applying basic text styles, it doesn't render on the right like it does with `<div>`s. Using `<cite>` for quotes seems to fall more in-line with how many in the Obsidian community appear to use them, and at the moment, their positioning is a bit intrusive for the writing it's associated with.

Expected behavior:
![image](https://user-images.githubusercontent.com/77762275/106406972-7fb0c180-6400-11eb-940b-22246e3aa047.png)

Actual behavior:
![image](https://user-images.githubusercontent.com/77762275/106407030-97884580-6400-11eb-87ee-27d7a6cfe9ec.png)

I haven't tried anything yet due to a lack of time, though I think setting `display: block;` should allow for it to be positioned more easily.

**Comment by ArtexJay** [comment]
I didn't even know about the <cite></cite> option. I'll play around with it.

**Comment by Jexle** [comment]
Oh, the "incorrect" font isn't because of issues with the theme; the screenshots were just to show the positioning. I changed the font using a second class with `.signature`; if I take it off, it defaults back to Edwardian.

**Comment by ArtexJay** [comment]
Will be coming in v6, already have it "<cite></cite>" working on my working build
