### ISSUE TITLE
Misaligned custom checkboxes 

### ISSUE THREAD

**Issue by Mr-Tomato123** [ArtexJay/Obsidian-CyberGlow#40]
Whan using the custom checkboxes option through Style Settings plugin, the symbols inside the checkboxes are misaligned.

Example
![IMG_0066](https://user-images.githubusercontent.com/121110164/216326481-36d128a0-e1f4-4099-8810-3c91fbc80f46.png)

**Comment by ArtexJay** [comment]
You're right that's weird.
Tried it on my tablet and phone (No plugins except for Style Settings), it looked normal. 
It appears however that the new width and height of the checkbox isn't rendering on the screen like it should. Was able to reproduce it on simulated tablet view with dev-tools on windows, by disabling the width and height i mentioned. So something might be interfering with the theme.

Do you have any checkbox plugins?

**Comment by ArtexJay** [comment]
> Whan using the custom checkboxes option through Style Settings plugin, the symbols inside the checkboxes are misaligned.
> 
> Example ![IMG_0066](https://user-images.githubusercontent.com/121110164/216326481-36d128a0-e1f4-4099-8810-3c91fbc80f46.png)

Update to the latest version and check it now. It should be good.
