### ISSUE TITLE
[Desktop Bug?] Tab Title Bar Overlaps Kanban List Titles

### ISSUE THREAD

**Issue by SuperDragonite2172** [ArtexJay/Obsidian-CyberGlow#45]
**Describe the bug**
Unsure if this is a bug or intentional design, but the tab title bar covers up the title of lists on Kanban boards (see screenshot below)

**To Reproduce**
1. Create or open a Kanban Board (Requires the Kanban plugin)
2. Add a list to the board.
3. Observe the overlap of the title bar.

**Expected behavior**
I was expecting there to be padding to prevent the overlap like with other themes.

**Screenshots, Gifs, Video**
![image](https://user-images.githubusercontent.com/14007732/219874887-4540ae2e-6c04-495a-b18f-966a744b05a9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: v1.1.9
 - CyberGlow Version: v7.8.0

**Additional context**
N/A

**Comment by ArtexJay** [comment]
This should be an easy fix.

I don't personally use Kanban so I'm expecting some things to not look right, like this for example. 
Please would be great help if you opened more issues on things that notice don't look quite right for Kanban or other plugins.

**Comment by ArtexJay** [comment]
I'll prepare an update for Kanban noticed a few other things too.

**Comment by SuperDragonite2172** [comment]
Thank you.  I just found your theme today and I immediately fell in love with it.  80s Neon and Obsidianite (two themes you mention as inspirations) are two of my favorite themes and your theme checked all the boxes.  Looking forward to seeing this theme get better.

**Comment by ArtexJay** [comment]
The next update will have Kanban, it will be coming soon. Keep an eye out for the update.

**Comment by SuperDragonite2172** [comment]
I look forward to it.  Thank you for dedicating time to this.

**Comment by ArtexJay** [comment]
> I look forward to it. Thank you for dedicating time to this.

New Update is out for this, update the theme and let me know if the issue was resolved for you.

**Comment by SuperDragonite2172** [comment]
The overlap is gone and looks consistent with the rest of the theme.  Thanks again for this addition.
