### ISSUE TITLE
[Desktop Bug] Obsidian Icon Changes To Default Icon On Hover

### ISSUE THREAD

**Issue by SuperDragonite2172** [ArtexJay/Obsidian-CyberGlow#47]
**Describe the bug**
When the Window Frame Style is set to `Obsidian` and you hover over the Obsidian Icon, it changes to the default icon.

**To Reproduce**
1. Set the Window Frame Style to `Obsidian` (Settings > Appearance)
2. Restart Obsidian to apply the setting.
3. Hover over the Obsidian Icon.
4. Observe the behavior

**Expected behavior**
Either the icon doesn't change, the icon inverts, or the icon changes to another icon.

**Screenshots, Gifs, Video**
![Shard](https://user-images.githubusercontent.com/14007732/221333544-45afa425-582f-4768-ad9c-5fdef4dece38.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: v1.1.15
 - CyberGlow Version: v8.7.5

**Additional context**
Branched from https://github.com/ArtexJay/Obsidian-CyberGlow/issues/46 at request of the repo owner.

**Comment by SuperDragonite2172** [comment]
If it's not too much effort to implement.  I don't want to take time away from "more important" features.  As I had had noted in the other issue I don't mind that it changes to default on hover since it's not something I do all the time.

**Comment by ArtexJay** [comment]
I will explore the other frames.
However I think I will focus for now on the hidden frame, plus I plan still on going through the entirety of the code to try to streamline and document it better first. I'll keep this open so that I address it when i get around to it.

**Comment by ArtexJay** [comment]
This custom icon support has been implemented.
