### ISSUE TITLE
[Desktop Bug] bold and italics exporting to pdf visual bug

### ISSUE THREAD

**Issue by d3aths** [ArtexJay/Obsidian-CyberGlow#48]
**Describe the bug**
When having a note using the custom bold and italics texts, exporting it to pdf will make the bolded/italiced text just display as a blue box

**To Reproduce**
make some text bold or italic
export the note to pdf
open to view

**Expected behavior**
that it would be exported out to appear as it does in reading view

**Screenshots, Gifs, Video**
![image](https://user-images.githubusercontent.com/16113944/221741500-2f7b08ce-cc09-4531-b0b5-0075b3255a7f.png)
**Desktop (please complete the following information):**
 - OS: kali linux
 - Obsidian Version: 1.1.9
 - CyberGlow Version: 7.8.8

**Additional context**
this could also just be a pdf limitation, if so then feel free to close the issue but it would be great if the pdf actually came out looking as polished as reading view does

**Comment by ArtexJay** [comment]
that's weird, i tried exporting it myself and was unable to replicate this (see screenshot below) I tried Foxit Reader and Chrome/Edge built in PDF viewer.
Could you check if you have any plugins that in anyway influence the pdf exporting?
Or what PDF reader do you use?

![image](https://user-images.githubusercontent.com/32932497/221981524-c02c9050-ef9d-4459-b4d0-38a18bb13cab.png)

**Comment by ArtexJay** [comment]
Otherwise it may be a limitation from Obsidian on Linux. I haven't tried my theme on Linux or Mac (don't have any device running either of those OS.) If that's the case I'll see if there's a way in CSS to differentiate between Linux and remove the gradient styling for that OS.

**Comment by ArtexJay** [comment]
Please update the theme to v7.9.0 either via obsidian or manually, and verify if that issue has been resolved.
If not I will provide you with a snippet for you to test that should resolve it.

**Comment by d3aths** [comment]
just updated it, the issue persists. the pdf reader is the default one, Evince document reader for gnome. I did try opening the pdf in firefox though, which displayed the bond text correctly, so it's probably just something within evince itself that can't read it properly.

**Comment by d3aths** [comment]
![image](https://user-images.githubusercontent.com/16113944/226222574-1db6cf0c-d5a4-4758-a9c8-c0d96c9a8e0c.png)
clip from a pdf export with this fix.
while it doesn't make the background transparent like it aims to, it's suitable for actually being able to read it. still weird that it displays this behaviour in the first place though

**Comment by ArtexJay** [comment]
Definitely, no idea why there's this issue for some pdf viewer/readers.
But like I said, I will be changing the stylings of bold and italics to be a bit more simple as to avoid these incompatibility with some readers.
Hopefully this fix is good enough for you for now, until the rework is done. If it isn't you can remove the styling from the theme, I can tell you what code specifically you need to remove.

**Comment by d3aths** [comment]
It's all good for now, tbh i really like the blue gradient style and mostly use obsidian in reading/edit mode cause i'm doing my project journals for uni with it, so i still get to look at all the good styling stuff. thanks!
