### ISSUE TITLE
Pop Out/New Windows are not styled[Desktop Bug]

### ISSUE THREAD

**Issue by AKasera** [ArtexJay/Obsidian-CyberGlow#49]
**Describe the bug**
When a file is popped out or moved to new Window, it appears unstyled with a basic white font and dark background and none of the cyber glow

**To Reproduce**
1. Open Obsidian
2. Right Click a File and Open in New Window

**Expected behavior**
File should have opened and be styled the way Cyberglow is meant to be

**Screenshots, Gifs, Video**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version 1.1.16
 - CyberGlow Version 7.9

**Additional context**

**Comment by ArtexJay** [comment]
Yea, i noticed it  https://github.com/ArtexJay/Obsidian-CyberGlow/issues/41.

I am attempting to resolve this in the rework. Though the rework is taking quite a bit of time.

**Comment by ArtexJay** [comment]
I found the issue for this apparently ".ͼ1 " breaks all CSS styles for popout windows. Deleting all instances of ".ͼ1 " in the CSS code appears to resolve the bug. 
I will try to find ways to mitigate or avoid this issue with css.
Next release will have the style working again on the popout window
