### ISSUE TITLE
Heading 4 reading view font-size too small

### ISSUE THREAD

**Issue by hanconel** [ArtexJay/Obsidian-CyberGlow#52]
**Describe the bug**
Heading 4 Font-size is too small compared to Heading 5 and 6 when in reading mode.

**To Reproduce**
1. Go to Obsidian and open a note.
2. Type #### Heading.
3. View in Reading Mode.
4. Compare heading 4 font-size with heading 5 & 6.

**Expected behavior**
A larger font-size than heading 5 & 6.

**Screenshots, Gifs, Video**
![obsidian h4 reading view font size](https://github.com/ArtexJay/Obsidian-CyberGlow/assets/133162292/8b3e2b8a-ddae-46d0-9be7-2db5cd21cebc)
![h4 reading view font-size](https://github.com/ArtexJay/Obsidian-CyberGlow/assets/133162292/2f4db3a3-6218-480d-8382-981c4f4a41b2)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version v.1.2.8
 - CyberGlow Version v7.9.0

**Additional context**
Go to theme.css .vertical-tab-content h4 and adjust font-size for theme.

**Comment by ArtexJay** [comment]
Oh damn, how did i miss this, ill include it in the next release.

**Comment by ArtexJay** [comment]
It has been resolved and will be included in the Rework v8 Update that will be coming soon.
