### ISSUE TITLE
[Mobile Bug]

### ISSUE THREAD

**Issue by Mr-Tomato123** [ArtexJay/Obsidian-CyberGlow#53]
**Describe the bug**
The "search" button is inaccessible due to the search header overlapping it

**To Reproduce**
1. Go to the left sidebar to the files/search/tags/bookmarks section
2. Click on search
3. Try to click on search (it is hidden under the heading

**Screenshot**
![image](https://github.com/ArtexJay/Obsidian-CyberGlow/assets/121110164/13dc3936-74ae-4488-b36a-9b38530bfe86)

**Mobile (please complete the following information):**
 - OS: iPadOS 16.3.1
 - Device: iPad 9
 - Obsidian Version v1.4.4
 - CyberGlow Version 7.9.0

**Comment by ArtexJay** [comment]
I'll try to reproduce it when I am able to

**Comment by ArtexJay** [comment]
This also affects the phone version of the theme, and I have resolved it. Please wait for v8 update, it should come at the end of this month.
