### ISSUE TITLE
[Desktop Bug]Local file url link doesn't work.

### ISSUE THREAD

**Issue by GodExious** [ArtexJay/Obsidian-CyberGlow#54]
**Describe the bug**
In [StyleSettings -> CyberGlowTweakbox -> BackgroundControls -> CustomWorkspaceBackgoundImage], I have already set all formats of the local file link, but it doesn't work. But the remote url such as [url("https://XXX.XXX.XXX")] can work.

The ineffective formats I have tried are as follow:
- `D:/1.png`
- `D://1.png`
- `file:///D://1.png`
- `file://D://1.png`
- `url("D://1.png")`
- `url("D:/1.png")`
- `url("file:///D://1.png")`
- `url("file://D://1.png")`
- `url("app://1.png/")`
- `url("app://D:/1.png/")`
- `url("app://D/1.png/")`

Also, I tried the respective path under obsidian workspace:
- `1.png`
- `./1.png`
- `url("1.png")`
- `url("./1.png")`
- `url("./1.png")`
- `url("app://1.png/")`
- `url("app://./1.png/")`

So I want to know what's the correct format for local background image file.

**Comment by ArtexJay** [comment]
As of Obsidian 1.2.8 local file URLs are no longer supported natively in Obsidian. 
Source: https://forum.obsidian.md/t/obsidian-release-v1-2-8/59086

I haven't been following Style Settings, so I do not know if they updated to have support for local links within the Style Settings plugin or if they have an alternate file url expression that one can use.
You can find Style Settings repo here: https://github.com/mgmeyers/obsidian-style-settings
I think this issue here is what you're looking for https://github.com/mgmeyers/obsidian-style-settings/issues/118

**Comment by GodExious** [comment]
> As of Obsidian 1.2.8 local file URLs are no longer supported natively in Obsidian. Source: https://forum.obsidian.md/t/obsidian-release-v1-2-8/59086
> 
> I haven't been following Style Settings, so I do not know if they updated to have support for local links within the Style Settings plugin or if they have an alternate file url expression that one can use. You can find Style Settings repo here: https://github.com/mgmeyers/obsidian-style-settings I think this issue here could be relevant to what you're looking for [mgmeyers/obsidian-style-settings#118](https://github.com/mgmeyers/obsidian-style-settings/issues/118)

Thank you for your answer. Maybe it's more suitable to issue it in StyleSettings repo.

Buy the way, the background image in your illustration is so beautiful, can I brazenly ask you for the image's url? Which image I describe is this light one:

![Screenshot](https://user-images.githubusercontent.com/32932497/221440386-0dd9712d-e6d4-4321-bc3a-30faa1d9be65.png)

**Comment by ArtexJay** [comment]
> Thank you for your answer. Maybe it's more suitable to issue it in StyleSettings repo.
> 
> Buy the way, the background image in your illustration is so beautiful, can I brazenly ask you for the image's url? Which image I describe is this light one:
> 

Of course!  Both the light and dark in the screenshot uses the same image as a background.
I got the image from deviantart and used it as my personal desktop wallpaper for a bit and thought it would look amazing on Obsidian for my theme. The artist makes really beautiful art on DeviantArt. This one was an humanized Moltres from Pokemon flying in the sky. 
https://www.deviantart.com/sakimichan/art/Go-623780055
