### ISSUE TITLE
[Desktop Bug] A simple Typo 

### ISSUE THREAD

**Issue by Xelbayria** [ArtexJay/Obsidian-CyberGlow#61]
**Describe the bug**

There is a typo (Idk what to call it) in your variable `var(--inactivetab);` via [Location](https://github.com/ArtexJay/Obsidian-CyberGlow/blob/e39be88400a9eb37302216f1eb88a2942cb4ab26/theme.css#L706-L710)

a few weeks ago, I noticed the variable `--Inactive-title)` is not being used. I believe that the correct variable should be `var(--Inactive-title);` via the said location that targeted the inactive title

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots, Gifs, Video**

**Desktop (please complete the following information):**
 - OS: Not Necessary
 - Obsidian Version: Not Necessary
 - **CyberGlow (Since v8.0.0)**

**Additional context**
N/A

**Comment by ArtexJay** [comment]
Both --inactive-title and --inactivetab are in use.
--inactive-title is for the note title seen here:
![image](https://github.com/ArtexJay/Obsidian-CyberGlow/assets/32932497/8c1435e4-91fc-42b1-90f1-7a1025a032cf)

--inactivetab is the text within the inactive tab. Which is the only thing that can be colored in an inactive tab.

**Comment by Xelbayria** [comment]
> Both --inactive-title and --inactivetab are in use. --inactive-title is for the note title seen here: ![image](https://user-images.githubusercontent.com/32932497/270131680-318d517e-e792-4d7f-a8d9-dc10c01a7b89.png)
> 
> --inactivetab is the text within the inactive tab. Which is the only thing that can be colored in an inactive tab.

Ah, I understand now.
