### ISSUE TITLE
Network usage is prohibited for themes

### ISSUE THREAD

**Issue by joethei** [ArtexJay/Obsidian-CyberGlow#62]
It appears that your theme uses network connections to load assets (e.g. fonts, icons, or images). This is prohibited by the official [Obsidian developer policies](https://docs.obsidian.md/Developer+policies) because themes should function completely locally.

You can bundle an asset for local use by using data URLs. [See this guide](https://docs.obsidian.md/Themes/App+themes/Embed+fonts+and+images+in+your+theme). 

Please let us know if you have any questions. Any themes that use network connections will be removed from the official directory in the first week of January 2024.

- The Obsidian team.

**Comment by ArtexJay** [comment]
> It appears that your theme uses network connections to load assets (e.g. fonts, icons, or images). This is prohibited by the official [Obsidian developer policies]
> Please let us know if you have any questions. Any themes that use network connections will be removed from the official directory in the first week of January 2024.

This should be now a non-issue with the release of v8.1.9 of my theme. I have removed all url links to external websites. If i happen to have missed any, which i don't think I have let me know so i can patch it out.

**Comment by ArtexJay** [comment]
Closing this has there have been no responses from you (@joethei), so after update v8.1.9 which removed the link to the resources in question, I assume that you or other Obsidian staffers would find that this theme now conforms correctly to the new policy.
