### ISSUE TITLE
Non-existent Space Displayed After Colon In Different Scenarios, Not Others:

### ISSUE THREAD

**Issue by di-org** [ArtexJay/Obsidian-CyberGlow#70]
For these findings, I created a new vault and tested 1) with default theme, then 2) applied only Cyber Glow theme.  No other changes were made to the vault.

There are inconsistencies in how text displays after a colon (:) is typed.  The results vary depending on what follows the colon, regardless of what precedes a colon (number, special character, upper or lower case letter).

- Space displayed when typing as follows:
  - Colon followed by a number.
    - typing "10:10" displays as "10: 10"
    - typing "A:10" displays as "A: 10"
    - typing "a:10 displays as "a: 10" \* (other odd behavior, see asterisk line in the notes.) 
    - typing "-:10" displays as "-: 10"
  - Colon followed by an uppercase letter.
    - typing "10:A" displays as "10: A"
    - typing "A:A" displays as "A: A"
    - typing "a:A" displays as "a: A" \* (other odd behavior, see asterisk line in the notes.)
    - typing "-:A" displays as "-: A"

**To note:**
- This does not occur with the default theme.
- This does not occur when the colon is followed by a lower case letter or ASCII special character.
  - After typing the colon, you can see the cursor as if a space has been added, but if typing lower or ASCII special char, the space is removed.
- This does not occur in headings:
  - Typing "## 10:10" displays as "10:10" in the heading font size.
- Displays the same in edit or reading mode.
  - \* However, after switching from edit -> reading mode, the lower case letter - colon - upper case or number chars removes the space, and the space does not return after switching back to edit mode:
    - Typing "a:10" displays as "a: 10", then switching to reading mode it is **now** displayed as "a:10". 
    - This does not happen with special characters, upper case, numbers, or non-ASCII UTF-8 characters: "A: 10", "A: A", "10: 10", "10: A", "-: 10", "-: A", "A: ᦦ", "10: ᦦ" keep the non-existent space after switching to reading and back to edit. 
    - Viewing the .md file in a text editor shows no space between the colon and the characters that follow it, despite the display of a space. 

I ran a couple of additional tests after submitting this report, but didn't want to fit it into the above notes:
- I tried numerous non-ASCII UTF-8 characters after the colon and the results are the same (e.g. ᦦ and Č), except with the lowercase / special chars - colon - non-ASCII UTF-8 chars, which do not add the non-existent space.
  - typing "10:ᦦ" displays as "10: ᦦ", "A:ᦦ" displays as "A: ᦦ" - but "a:ᦦ" or "-:ᦦ", both display no space: "a:ᦦ" & "-:ᦦ".
- Typing with a non-ASCII UTF-8 character before the colon results in a space only when followed by a number:
  - "ᦦ:10" displays "ᦦ: 10"
  - "ᦦ:A" displays "ᦦ:A"
  - "ᦦ:a" displays "ᦦ:a"
  - "ᦦ:-" displays "ᦦ:-"
  - "ᦦ:ᦦ" displays "ᦦ:ᦦ"
  - Switching from edit mode to reading and back does not alter the text display.

Everything to this point occurs the same on mobile.

**Expected behavior**
No space, to preserve the actual text being typed.

**Screenshots, Gifs, Video**
See attached

**Desktop (please complete the following information):**
 - OS: Pop_!OS 22.04 & Calyx OS 5.3.0 (Android 14).
 - Obsidian Version: 1.5.3 (desktop), 1.4.16 (114) (mobile). 
 - CyberGlow Version 8.2.5

Screenshot, initial typing of examples, edit mode: 
![01-cyber_glow-edit](https://github.com/ArtexJay/Obsidian-CyberGlow/assets/41967712/7dcea62e-6caf-4789-9095-0c8ac9368842)

Screenshot after switching to reading mode (note "a: 10" &"a: A" changed to "a:10" & "a:A":
![02-cyber_glow-reading](https://github.com/ArtexJay/Obsidian-CyberGlow/assets/41967712/6a18e581-bccc-4eee-8f4b-b9da0b47897a)

Screenshot after switching back to edit mode.
![03-cyber_glow-back2edit](https://github.com/ArtexJay/Obsidian-CyberGlow/assets/41967712/fc01bc0f-289d-43ca-921c-cfb96ed7d4f3)

Screenshot of the markdown file in text editor Pluma.  Note that none have spaces.
![04-markdown_in_txt_editor](https://github.com/ArtexJay/Obsidian-CyberGlow/assets/41967712/173c1c33-45ed-4231-bfaa-64212216cdab)

Screenshot of number, upper case, lower case - colon - non-ASCII UTF-8 character.
![05-cyber glow-lower_case-colon-UTF-8-char](https://github.com/ArtexJay/Obsidian-CyberGlow/assets/41967712/bb9781b7-6fb2-4149-87bf-09915d0ff116)

Love the theme!
Andy

**Comment by ArtexJay** [comment]
This is a custom font issue. I'll fix this issue in the font file itself though and update the theme with it when I can.

Short term fix would be to change the font by going into Settings  -> Appearance -> "Text Font", change add any font that is installed on your system and it will override the custom theme font.

**Comment by ArtexJay** [comment]
Managed to fix this issue in the font itself. There will be an update this week with the fix.

**Comment by di-org** [comment]
Thanks ArtexJay, for the workaround and fix.  I do dig the font you've chosen, so I appreciate the effort.

**Comment by ArtexJay** [comment]
Update the theme, the issue should be resolved now.
