### ISSUE TITLE
[Desktop Bug] Accents (font issue)

### ISSUE THREAD

**Issue by Nemipune** [ArtexJay/Obsidian-CyberGlow#73]
**Describe the bug**
I write in french and the grave accent on letters like `à, è and ù` that are used all the time are displayed on the next character (see attached files).
I see this in the main text and in the page/folder titles.

**To Reproduce**
1. Open Obsidian with the cyberglow custom font
2. Type any letter containing a grave accent in any text field

**Expected behavior**
The accent should be on the proper character, not the next one

**Screenshots, Gifs, Video**
![2024-02-20_18-51](https://github.com/ArtexJay/Obsidian-CyberGlow/assets/146527960/33850fbc-c66f-48ff-a8a7-61d1baab45ce)
![2024-02-20_18-54](https://github.com/ArtexJay/Obsidian-CyberGlow/assets/146527960/7001c865-5c77-462d-8f09-fa3c3e4a3ff1)

**Desktop (please complete the following information):**
 - OS: EndeavourOS (arch-6.7)
 - Obsidian Version: v1.5.3
 - CyberGlow Version: v8.2.5

**Additional context**
Besides this small issue, awesome theme and font, thanks a lot for the good work !

**Comment by ArtexJay** [comment]
This is a custom font issue. Apologies for neglecting accented letters. I'll fix this issue in the font file itself as soon as possible and will update the theme soon. 

Short term fix would be to change the font by going into Settings -> Appearance -> "Text Font", add any font that is installed on your system, and it will override the custom theme font.

Expect a fix for this in the next release after 8.2.6.
