### ISSUE TITLE
Heading Identifier Displays Differently When Containing Tags, Based on Number of Spaces.

### ISSUE THREAD

**Issue by di-org** [ArtexJay/Obsidian-CyberGlow#75]
This is very low priority - maybe the lowest:

I was creating an H3 heading, which started with a tag ( a person's #firstname_lastname ), and noticed that it displays differently of there is only one [[SPACE]] between the heading and the tag, vice two spaces:  with 2 spaces, the heading identifier looks normal (big "H3 w/ 1, small "H3" w/ 2, in this example).  Samples:

"### #john_doe" (One Space)
"###  #john_doe" (Two Spaces)

Not sure of this is fixable or not, as not a MD expert.  See screenshot below:

![obsidian_heading_and_tags](https://github.com/ArtexJay/Obsidian-CyberGlow/assets/41967712/44935b8b-4aaa-4baf-a98b-a1d6d53fad47)

**Comment by ArtexJay** [comment]
I have exams very soon, so I will look into this after that.
Can you quickly check if the Default Obsidian theme has this same problem? If it does, then this might not a theme issue.

**Comment by ArtexJay** [comment]
I managed to find a suitable fix, I am planning on releasing a new update very soon

**Comment by ArtexJay** [comment]
Just released the newest update, you will need to reinstall the theme
