### ISSUE TITLE
CyberGlow - High GPU and Battery Consumption 

### ISSUE THREAD

**Issue by OdiJordan** [ArtexJay/Obsidian-CyberGlow#80]
I don't know if this is the proper way to address this issue, but since I'm a huge fan of this theme overall, I thought I'd give it a try and post this here, I had this theme installed since couple of days on my PC, today I decided to apply it on my Laptop, Ran Obsidian as usual and installed on my Lenovo ThinkPad that I use for work mainly. 

The moment I applied the theme while still on the settings window too, my laptop fans fired up and sounded awfully loud, I instantly opened my task manager on windows, to see that my GPU consumption is around 80% from obsidian alone, in the background without typing a word on it! 

Technically my laptop has an integrated (Intel Xe Graphics) / 12th Gen. i7 CPU, which is more than enough to do whatever I do, but that's probably why I didn't notice this issue at all on my desktop back home, I switched to the default theme, and all came back fine. 

Please check the screenshot from my task manager attached to this.

**Expected behavior**
I really hope there can be a work around this to use my favorite theme without draining my laptop's battery in less than 3 minutes.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 23H2
 - Obsidian Version 1.5.12
 - CyberGlow Version 1.3.2

![image](https://github.com/ArtexJay/Obsidian-CyberGlow/assets/115042687/f09e7440-7d61-4ae3-9304-1a7056fd0008)

**Comment by usualstuff** [comment]
Hey there, did you managed to solve the issue? I cant use the theme on my phone because of this.

**Comment by ArtexJay** [comment]
You can try to fix the issue by disabling custom background image, which can help.

Ive noticed this issue myself and plan on reconstructing my theme to check what exactly causes this issue, though Im quite certain its custom background image setting that causes the lag. Going forward I will most likely disable that setting by default if Style Settings is installed.

**Comment by ArtexJay** [comment]
I am currently looking through the code and monitoring activity in task manager, I'll put out an update that addresses this soon.

**Comment by ArtexJay** [comment]
The code I found that was causing excess power draw on idle was a small animation. With it enabled saw task manager CPU usages on my laptop spike from near 0% to around 5% or so. This animation code will be disabled and have an option to enable it in style settings with a warning note to it.
Hunting around for any other code that could be a contributor as well.

**Comment by ArtexJay** [comment]
@usualstuff  @OdiJordan  Just released a massive update with lots of changes and improvements, I have been carefully monitoring the task manager, and I am happy to report that this version uses same number of resources as the vanilla theme on idle thus it should be easier on your system resources and battery now.

Please give it a try and let me know what you think now

**Comment by usualstuff** [comment]
@ArtexJay Absolutely wonderful job! I checked my PC and phone - no battery drain issues. 

Thank you so much, big fan of your theme!

**Comment by ArtexJay** [comment]
> @ArtexJay Absolutely wonderful job! I checked my PC and phone - no battery drain issues.
> 
> Thank you so much, big fan of your theme!

Yaaaay, thats great to hear! And very glad you like my theme, it means a lot.
