### ISSUE TITLE
No Icon in Horizontal Rule

### ISSUE THREAD

**Issue by sqeptyk** [ArtexJay/Obsidian-CyberGlow#84]
I've been using your theme since I started using Obsidian and love every single thing about it except the horizontal rule.  Is there a way to just display an uninterrupted line as seen with the headers?
![HRstyle](https://github.com/user-attachments/assets/c4d81036-24ca-46e9-8ce9-61d2ced2ff56)

**Comment by ArtexJay** [comment]
Not at this time, I will be sure to make an option for it, I will update this thread once I have

**Comment by sqeptyk** [comment]
Thank you much and thank you for the theme.

**Comment by ArtexJay** [comment]
the update is up
