### ISSUE TITLE
[Desktop Bug] Need to Disable and Enable "Enable Workspace Background" to Appear

### ISSUE THREAD

**Issue by johnsbuck** [ArtexJay/Obsidian-CyberGlow#86]
**Describe the bug**
When installing the theme, instead of getting the expected background shown in the example images, you get a black background.

![image](https://github.com/user-attachments/assets/39be4ca2-a23d-4109-ad67-869794f9f5a7)

To enable the background, you need to have Style Settings install and go into Background Controls, but in there it will show that _Enable Workspace Background_ is enabled.

![image](https://github.com/user-attachments/assets/c1f0817a-209b-4771-8837-e2a75394b6e0)

To get the background enabled, you have disable and then re-enable _Enable Workspace Background_.

![image](https://github.com/user-attachments/assets/6fcc927c-1f2f-42eb-8821-6b39152d0aef)

![image](https://github.com/user-attachments/assets/c69ea3f6-9d64-4a60-bc9d-4a6a55372b0d)

If you press the restore default button, it will put it back in this "Enabled, but actually Disabled" state.

![image](https://github.com/user-attachments/assets/6ec48e08-7e17-4164-88f9-6c65928738a0)

**To Reproduce**
Reproduction part of description to show issues with menu. Will add detailed instructions here.

_Error Reproduction:_ Default Settings Are Misaligned
1. Install Style Settings plugin
2. Install theme
3. **Error:** No default background
4. Go to Style Settings plugin page
5. Go to **Cyber Glow Tweakbox -> Background Controls**
6. **Error:** Notice _Enable Workspace Background_ is set to enable, but no default background.

_Error Reproduction:_ Fixing Error with Background **_(continuing from previous error)_**
7. Disable & Enable _Enable Workspace Background_
8. Notice default background is now visible.
9. Press _Restore default_ button next to _Enable Workspace Background_
10. **Error:** _Enable Workspace Background_ is enabled, but background is not visible.

**Expected behavior**
Two expectations:

1. I expect the default background to be available upon installation (with or without Style Settings)
2. I expect pressing the _Restore default_ button next to _Enable Workspace Background_ would set it in an enabled state, which would leave the background visible.

**Screenshots, Gifs, Video**
Screenshots shown in description to describe series of events.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version v1.6.7
 - CyberGlow Version v1.3.7

**Additional context**
No additional context to report.

**Comment by johnsbuck** [comment]
It's easy to miss, but if you look at the two images after the **_To get the background enabled, you have disable and then re-enable Enable Workspace Background_** section, you can see when enabling the background changes to the default background as expected.

**Comment by ArtexJay** [comment]
Sorry just saw this now, havent been on for a bit, released a new update with a few fixes this one included
