### ISSUE TITLE
[Desktop Bug]  Excalidraw plug in color picker

### ISSUE THREAD

**Issue by GunniBlo** [ArtexJay/Obsidian-CyberGlow#88]
**Describe the bug**
when you use the plug in "Excalidraw", the color picker always shows white (when in dark mode) and black (when in light mode) when it should show the color you are picking 

**To Reproduce**
1. Go to 'an Excalidraw canvas/drawing'
2. Click on 'edit (after you've set some line or text on the canvas)'
4. you should see that the color picker only shows white (when in dark mode)

**Expected behavior**
you should see the correlated color on the box that should be selected

**Screenshots, Gifs, Video**
![image](https://github.com/user-attachments/assets/aa77f185-54e8-4033-9710-78d31c2081ed)

![image](https://github.com/user-attachments/assets/3144026c-55a2-4418-95a0-55fa502fc8fa)

![image](https://github.com/user-attachments/assets/c428a6f5-3fb2-400c-be68-7cd446e9d688)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Obsidian Version [ v1.6.7 ]
 - CyberGlow Version [ v8.2.5 ]

**Additional context**
this is minor but rather annoying. would be much better if I could see the color I am picking. 
I have bought you a pizza 
I love this theme. hope you will fix this :) 
thanks in advance

**Comment by ArtexJay** [comment]
I'll look into it, will try to update it soon.

**Comment by ArtexJay** [comment]
You have to update the CyberGlow Obsidian theme, you are running an old version. Because I revised the versioning to be more consistent, you will have to uninstall and reinstall the theme.

Your issue however is still present in a different way. I will push an update soon.

**Comment by ArtexJay** [comment]
Update the theme to the latest v1.4.0

**Comment by GunniBlo** [comment]
yeah, sorry.  I didn't see the second comment you made. 
I did try to update the theme in obsidian and it said it was in 1.4.0 and it still didn't work, so I uninstalled it and reinstalled it and now it works. thanks a lot.
