### ISSUE TITLE
[Font] All fonts are now "Inter" as of Obsidian 1.7.4.

### ISSUE THREAD

**Issue by CaptainBetts** [ArtexJay/Obsidian-CyberGlow#90]
**Describe the bug**
After Obsidian updated to 1.7.4, all fonts reverted to "Inter".

**To Reproduce**
Open up any note. All fonts are now "Inter".

**Screenshots, Gifs, Video**
![image](https://github.com/user-attachments/assets/db390313-8728-4401-ac4a-bc768955389e)

**Desktop (please complete the following information):**
 - OS: Mac OS 14.6.1 (23G93)
 - Obsidian Version Version 1.7.4 (Installer 1.6.7)
 - CyberGlow Version 1.4.0

**Additional context**
I have tried rebooting Obsidian, and uninstalling and reinstalling Cyberglow.

**Comment by ArtexJay** [comment]
Good catch, somehow, I totally overlooked this. I'll try to figure out a fix for it and release it soon.

**Comment by ArtexJay** [comment]
Just to clarify on your end, only the notes are using the Inter font correct? If yes, then I see that as well.

But, the interface font (font in the file explorer, titlebar, popup for example) is still using the correct font?

**Comment by ArtexJay** [comment]
I pushed out a small update, font issue should be fixed now
