### ISSUE TITLE
very good features!!

### ISSUE THREAD

**Issue by Kryxzort** [ArtexJay/Obsidian-CyberGlow#92]
Basically, 

Feature: give us the ability to hide/unhide the chevron
Feature: hide/unhide the folder icon at the left of the folder names
Feature: give us the ability to change bold text color and glow
Bug: there is a box around the place chevron was originally supposed to be, it becomes visible when you hover over that area

I have done all this and made this into a snippet, also even added toggles and color pickers for all of these, you can probably do a better and more optimized version but till then:

[Cyber glow snippet.txt](https://github.com/user-attachments/files/17848045/Cyber.glow.snippet.txt)

**Change the txt file extension to CSS, So Cyber glow snippet.txt into Cyber glow snippet.css**
I had to make it txt cuz GitHub don't allow CSS

**Comment by ArtexJay** [comment]
I have been for the past few months been slowly and methodically going through my theme, update certain visuals, fix bugs that I can identify and especially fix that significant lag which I believe I have resolved and bring it further up to date to the current Obsidian UI version. 

Chevron bug has been resolved in version I am currently working on as well as in some cases an unintended hidden chevron bug.

I havent looked at your snippet just yet, but could you tell me in which view youd want to hide or unhide chevron? 

"hide/unhide the folder icon at the left of the folder names" as of right now the folder icon is what replaces the chevron in this theme, so do you just want it be disabled or disabled with the return of the chevron?

for the 3rd option, just to clarify, do you mean change the text color and glow for bold text only? as of right now the color of the text depends on if youre on dark or light mode and glow color depends on the chosen accent color.

**Comment by ArtexJay** [comment]
I have adapted what you wrote in your snippet into the theme, it will be present in the upcoming release

**Comment by Kryxzort** [comment]
very happy to hear that. thank you for your time.
