### ISSUE TITLE
[Desktop Bug] border-left coming from somewhre

### ISSUE THREAD

**Issue by tu2-atmanand** [ArtexJay/Obsidian-CyberGlow#96]
**Describe the bug**

I haven't gone to the root cause of this issue, but looks like that `border-left` is coming from somewhere if its not from this plugin style.css.

I also havent tested this on mobile, so dont know if its on Mobile as well.

**Expected behavior**

Just dont need that `border-left` at all.

**Screenshots, Gifs, Video**

https://github.com/user-attachments/assets/e5ad1e8b-6f88-4fe1-ac47-5692acfbdc63

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version : 1.7.7
 - CyberGlow Version 2.0.0

**Comment by ArtexJay** [comment]
need more info, looks like this is with gutter line disabled right?

**Comment by ArtexJay** [comment]
I'll look into this, I recognize the element your disabling the border-left from, its a new addition seems to be causing some issues with notes as youve shown in your video

**Comment by ArtexJay** [comment]
For now, a temporary fix would be to go into the settings of obsidian, go to Editor tab and enable "Show number line"

**Comment by 0Zenchi** [comment]
I believe I do have this issue too. I saw, downloaded and configured the theme today, as I instantly fell in love with it.
But I did notice that not only the side panel (as you showed in the video) "consumes" the note on the left, as I also believe that that's the case generally for notes that get "too close to the wall" in a sense. 
![{0687D307-0BE8-4D4F-8BDC-5E0B28338454}](https://github.com/user-attachments/assets/d87a0412-120f-4f7b-bc1c-bebd824187a7)
In this image I'm showing the right panel, the things which I circled in blue and am pointing at, is a numbered list. on the bottom you can see 0, 1, 2 but that's from 10, 11, 12..

**Comment by ArtexJay** [comment]
@julroger2013 @jwhonce @0Zenchi I have a fix done for this, I expect to release the new update either tomorrow or on monday
