### ISSUE TITLE
[Desktop Bug] Theme Note Adjusting to Narrow Panes

### ISSUE THREAD

**Issue by julroger2013** [ArtexJay/Obsidian-CyberGlow#99]
**Describe the bug**

When using the theme on my Windows 11 Desktop PC, I notice that the arrangement of the text/headers/etc. doesn't seem to adjust when a pane is narrower than the normal readable line length.

In other words, instead of the text becoming narrower to fit inside the available space, it stays at the same width, which puts some of the text out of view.

This happens both when I have several narrow panes (as when I have three split panes in view, plus both side bars) or when I narrow the space the app itself occupies (like when I split screen Obsidian with another app).

**To Reproduce**

Either narrow the size of the Obsidian window, or else open up multiple split panes inside the app.

**Expected behavior**

The expected behavior is that the text narrow itself to fit within the width of the pane.

**Screenshots, Gifs, Video**

![image](https://github.com/user-attachments/assets/e3960072-e280-43c4-a468-ffc28673a6c1)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Obsidian Version 1.7.7
 - CyberGlow Version: Current (Just attempted update to confirm)

**Comment by ArtexJay** [comment]
I tried it on my end, and I cannot replicate this, all text correctly wraps when the panes are resized.

I had 3 pages open side by side, with both side panels opened and resized the pages in read and live edit.

**Comment by julroger2013** [comment]
Hmmm. I’ll try disabling plugins and see if one is causing this. However, I noticed this only happened with CyberGlow. So it could be a plugin + the theme somehow. I’ll see what I can figure out

**Comment by ArtexJay** [comment]
if you find out if its a plugin, let me know.

Also Im not sure if it could be the case, but in CyberGlow with Style Settings you can modify the read length, which could be causing it?

**Comment by julroger2013** [comment]
I disabled every plugin, and also tried restricted mode. Neither one seemed to improve the issue.

I can't think of any appearance setting I've modified that would cause this issue. Resetting the readable line length didn't seem to make a difference. Neither did disabling Style Settings (which I assume would get rid of any changes that I might have made).

Any other ideas on what I can try? I'm still getting a little bit of the left margin chopped off. I don't have any CSS snippets enabled, so I can't think of what would be causing this.

**Comment by julroger2013** [comment]
It happens on the Sandbox Vault, too. I'm going to try reinstalling Obsidian to see if it's something unique/flawed about my installation.

**Comment by julroger2013** [comment]
Reinstalling the app didn't seem to help. 

I'm out of ideas. I'm on the 1.7.7 Obsidian, using Windows 11. I don't think there's anything unique about my version of Obsidian, or about my version of Windows 11, so I can't think of why the resizing would be a problem.

**Comment by julroger2013** [comment]
I guess I should be clear - it looks like the text does rearrange itself. It's just an issue with the left margin being cut off.

**Comment by ArtexJay** [comment]
> I guess I should be clear - it looks like the text does rearrange itself. It's just an issue with the left margin being cut off. And it appears only to happen in Live Preview mode. Things are laid out correctly in Reading mode.

ok, that narrows it down somewhat, at least we know now that this bug affects only live preview. I'll investigate on my end what could be causing this, may i ask what is your display resolution? As ive noticed some bugs on different screen size/resolution like icons shifting for example

**Comment by ArtexJay** [comment]
I know what the issue is now, seems that this is caused by a new addition to my theme that was imperfectly implemented. Another user made an issue on github that show your exact problem. I recognize the code that is affecting it so I'll look into it and issue a fix. 
Same as #96

**Comment by julroger2013** [comment]
Perfect, I’ll do that. Thank you!

**Comment by 0Zenchi** [comment]
oh yeah, It seems I have made this exact question in a section that was similar enough:

[](https://github.com/ArtexJay/Obsidian-CyberGlow/issues/96)

**Comment by ArtexJay** [comment]
@julroger2013 @jwhonce @0Zenchi I have a fix done for this, I expect to release the new update either tomorrow or on monday, together with some other fixes.

**Comment by ArtexJay** [comment]
@julroger2013 @jwhonce @0Zenchi the update has been released.

**Comment by julroger2013** [comment]
Confirming that this seems to be working properly now. I will circle back on this issue if further testing shows any other issues. Thank you! Love the theme
